<?php
// echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
// print_r($this->view);
// echo '</pre>';

?>

        <div class="product-status mg-b-15 ">
            <div class="container-fluid">
                <div class="row">
                <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="breadcome-heading">
                                       
                                            <span>
                                            <?php
                                                if(!empty($this->view['msg'])){
                                                    if(is_array($this->view['msg'])){
                                                        foreach ($this->view['msg'] as $item_msg)
                                                        echo '<b>'.$item_msg."</b>";
                                                    }else echo $this->view['msg'];
                                                }
                                                ?>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <ul class="breadcome-menu">
                                            <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                            </li>
                                            <li><span class="bread-blod">Đề thi</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>      
<div class="container-fluid">
    <div class="row">
        <h2 class="text-center">Thêm đề thi</h2>
        <form action="" method="post" >
            <div class="col-xs-6 col-xs-offset-3">
                <div class="form-group">
                    <label class = "require">Môn Học</label>
                    <select name="txt_ma_mh" id="select" class="form-control"  >
                    <?php

                    foreach($this->view['list_mh'] as $row){
                            if($row['ma_mh'] ==  $ma_mh)
                                $selected = ' selected ';
                            else
                                $selected ='';

                            echo '<option '.$selected.' value="'.$row['ma_mh'].'" >'.$row['ten_mh'].'</option>';
                        }
                    ?>
                    </select>    
                </div>     
                    <span id="btn_brows_question" style="cursor: pointer;color:red;font-weight: bolder" >Chọn câu hỏi...</span>
                <div class="form-group">
                    <label class = "require"> Kỳ Thi</label>
                    <select name="txt_ma_kt"  class="form-control">
                        <?php
                            foreach($this->view['list_kt'] as $row){
                                ?>
                                <option value="<?php echo $row['id_kt']; ?>"><?php echo $row['ten_kt']; ?></option>';
                                <?php
                            }
                        ?>
                    </select>
                </div>
                <div class="form-group">
                    <label class = "require">Tổng Điểm</label>
                    <input type="number"  required class="form-control" name="txt_tong_diem" />
                </div>
                <div class="form-group">
                    <label class = "require">Thời Gian làm bài</label>
                    <input type="number" required class="form-control" name="txt_thoi_gian_lam_bai" />
                </div>
            </div>
            <div class="col-lg-12">
                <div class="payment-adress mg-t-15 responsive-mg-t-0 mg-b-15">
                    <button type="submit" class="btn btn-primary waves-effect waves-light" title="Lưu" name="btnSave">Lưu</button>
                </div>
            </div>    
        </form>
    </div>
</div>
<script src="Public/Back-end/js/vendor/jquery-1.12.4.min.js"></script>

<script>
$(document).ready(function () {

    $('#btn_brows_question').click(function (event) {
        event.preventDefault();

    

        var monhoc = $('select[name="txt_ma_mh"]').val();
        window.open(window.location.protocol + "//" + window.location.host +_base_url+ "?controller=admin-exam&&action=list-ch&ma_mh="+monhoc,"popupWindow", "width=800,height=800,scrollbars=yes");
    });

    //save select value
    var subjectValue = localStorage.getItem("subjectValue");
    if(subjectValue != null) {
        $("#select").val(subjectValue);
    }

    $("#select").on("change", function() {
        localStorage.setItem("subjectValue", $(this).val());
        console.log($(this).val());
    });

// On change store the value




});
   
</script>
