
<?php

//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($this->view);
//echo '</pre>';

?>
<div class="clear"></div>
<div id="form_row">
    <form action="" method="post">
        <div class="manager-nav">
            <h2>
                <i class="fas fa-school></i> <a href="?controller=admin-hocphan&action=list">Quản lý Học Phần</a> 
                <span>
                    <?php
                    if(!empty($this->view['msg'])){
                            echo $this->view['msg'];
                    }
                    ?>
                </span>
            </h2>
        </div>
        <div class="form_row">
            <input type="hidden" name="txt_ma_hp" value="<?php echo @$this->view['data']['ma_hp'];?>">
            <?php
                if(isset($this->view['data'])){
                    echo '<h1>Bạn Chắc chắn Xóa Học phần:'.$this->view['data']['ten_hp'].'? </h1>';
                }
            ?>
        </div>
        <div class="form_row">
            <?php
            if(isset($this->view['data'])) {
                echo '<input type="submit" class="btn-delete" value="Đồng ý xóa" name="btnDelete" >';
                echo '<button class="btn-delete btn-return"><a href="?controller=admin-hocphan&action=list">Trở về</a></button>';
            }
            ?>
        </div> 

</form>

</div>
