<?php
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//print_r($this->view);
//echo '</pre>';?>
<div class="clear"></div>
<div id="form_row">
    <form action="" method="post">
    <div class="manager-nav">
            <h2>
                <i class="fas fa-school"></i> <a href="?controller=admin-hocphan&action=list">Quản lý Học Phần</a> 
                <span>
                    <?php
                    if(!empty($this->view['msg'])){
                        if(is_array($this->view['msg'])){
                             foreach ($this->view['msg'] as $item_msg)
                            echo '<b>'.$item_msg."</b>";
                        }else echo $this->view['msg'];
                    }
                    ?>
                </span>
                <span class="manager-item"><input type="image" src="Public/imgs/download.png" alt="SUBMIT" name="btnSave" />Lưu</span>
            </h2>
        </div>
        <fieldset>
            <legend>Sửa thông tin học phần</legend>
            <div class="form_row">
                <input  type="hidden" class="form_input" name="txt_ma_hp" value="<?php echo$this->view['data']['ma_hp'];?>" disabled>
                <label>Tên Học Phần</label>
                <input type="text" class="form_input" name="txt_ten_hp" value="<?php echo$this->view['data']['ten_hp'];?>">
            </div>
            <div class="form_row">
                <label>Môn Học</label>
                <select name="txt_ma_mh" style="    width: 500px;height: 34px;border-radius:5px;float: left;padding: 0px 0px 0 4px;background-color: #F4F6F7;border: 1px #90A9B7 solid;">
                <?php
                    foreach ($this->view['monhoc'] as $row){
                        echo '<option value="'.$row['ma_mh'].'">'.$row['ten_mh'].'</option>';
                    }
                ?>
                </select>
            </div>
            <div class="form_row checkbox">
            <input type="radio" name="khoa" id="" value='0' checked> Không Khóa
                    <input type="radio" name="khoa" id="" value='1'> Khóa
            </div>
        </fieldset>
    </form>
</div>




