<?php

// echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
// print_r($this->view);
// echo '</pre>';
?>
<div class="center_content">
    <div id="right_wrap">
        <div id="right_content">
        <h2><i class="fas fa-book"></i> Học Phần<a href="?controller=admin-hocphan&&action=add"><i class="fas fa-2x fa-plus-circle add-icon"> </i></a><a href="?controller=admin-hocphan&&action=add"><span class="themmoi">Thêm Mới</span></a></h2>
           
            <table id="rounded-corner">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>Tên Học Phần</th>
                    <th>Môn học</th>
                    <th>locked</th>
                    <th>Sửa</th>
                    <th>Xóa</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <td colspan="12"></td>
                </tr>
                </tfoot>
                <tbody>
                <tr class="odd">
                    <?php
                    $stt=0;
                    $img_delete='';
                    $img_not_delete='<img class="img_none"  src="Public/backend/images/none.jpg"';
                    $img_edit='<img src="Public/backend/images/edit.png"';
                    foreach($this->view['list'] as $row){
                        $stt++;
                        $link = '?controller=admin-hocphan&action=edit&id='.$row['ma_hp'];
                        $link_delete = '?controller=admin-hocphan&action=delete&id='.$row['ma_hp'];
                        if($row['locked']==1)
                        {
                             $img='<i class="fas fa-lock"></i>';
                             $img_delete = $img_not_delete;
                             $link_delete ='#';
                        }
                        if($row['locked']==0) {
                            $img='<i class="fas fa-lock-open"></i>';
                            $img_delete='<img src="Public/backend/images/trash.gif"';
                        }
                        echo '
                            <tr>
                                <td>'.$stt.'</td>
                                <td >'.$row['ten_hp'].'</td>
                                <td >'.$row['ten_mh'].'</td>
                                <td>'.$img.'</td>
                                <td><a href='.$link.'>'.$img_edit.'"  /></a></td>
                                <td><a href='.$link_delete.'>'.$img_delete.'"/></a></td>
                            </tr>';

                    

                    }
                    ?>

                </tr>
                <tr><td colspan="6">
                        <?php
                        // hiển thị chỉ số trang của danh sách
                        if($this->view['total_pages']>1){?>

                        <div class="page-number">
                            <ul>
                                <?php
                                for($page = 1; $page <=$this->view['total_pages'];$page++ ){
                                    echo '<li><a href="?controller=admin-hocphan&action=list&page='.$page.'">'.$page.'</a></li>';
                                }
                                ?>
                                <?php }?>
                    </td></tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="sidebar" id="sidebar">
        <h2>Quản lý</h2>
        <ul>
            <li><a href="?controller=admin-subject&action=list&page=1">Quản lý môn học</a></li>
        </ul>
    </div>
    <div class="clear"></div>
</div> <!--end of center_content-->
