<!-- <?php
echo '<pre>';
print_r($this->view);
echo '</pre>';
?> -->
        <div class="product-status mg-b-15 ">
            <div class="container-fluid">
                <div class="row">
                <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="breadcome-heading">
                                        <?php
                                            if(!empty($this->view['msg'])){
                                                if(is_array($this->view['msg'])){
                                                    foreach ($this->view['msg'] as $item_msg)
                                                    echo '<b>'.$item_msg."</b>";
                                                }else echo $this->view['msg'];
                                            }
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <ul class="breadcome-menu">
                                            <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                            </li>
                                            <li><span class="bread-blod">Câu hỏi</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <div class="container-fluid">
            <div class="row">
                <h2 class="text-center">Sửa câu hỏi</h2>
                <form action="" method="post" >
                    <div class="col-xs-6 col-xs-offset-3 ">

                        <div class="form-group">
                            <textarea id="content" required style="border:1px solid red;" name="txt_cau_hoi"><?php echo @$this->view['data']['noi_dung_ch'] ?></textarea>

                            <script type="text/javascript">


                                CKEDITOR.replace("content",{
                                    toolbar: [
                                        {name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat','-','Source']},
                                        {name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
                                        {
                                            name: 'insert',
                                            items: ['Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe']
                                        },
                                        {
                                            name: 'paragraph',
                                            items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
                                        },
                                        {name: 'links', items: ['Link', 'Unlink', 'Anchor']},
                                    ],
                                });</script>
                        </div>  
                        <div class="form-group">
                            <label class="require">Học phần</label>
                            <select name="txt_ma_hp" class="form-control">
                        
                            <?php
                                if(isset($this->view['list_hp'])){
                                    $id_hp = $this->view['data']['id_hp'];
                                    foreach ($this->view['list_hp'] as $row){
                                        if($row['ma_hp'] ==  $id_hp)
                                            $selected = ' selected ';
                                        else
                                            $selected ='';

                                        echo '<option '.$selected.' value="'.$row['ma_hp'].'" >'.$row['ten_hp'].'</option>';
                                    }
                                }
                                ?>
                            </select>
                        </div>
                        <div >
                            <label class="require">Độ khó</label>
                            <?php if(isset($this->view['data']['dokho'])){
                                $value =['de','tb','kho'];
                                $status = ['Dễ','Trung Bình','Khó'];
                                for($i=0;$i<3;$i++){
                                    if($this->view['data']['dokho']==$value[$i]) $checked = 'checked';
                                    else $checked ='';
                                    echo $status[$i].' <input type="radio" style="margin-right:10px"  name="dokho" value ='.$value[$i].' '.$checked.'/>';
                                }
                            } ?>
                        </div>
                        <?php
                        $noi_dung_dap_an = unserialize($this->view['data']['noi_dung_dap_an']);
                        for($i = 0; $i< 4; $i++){ 
                            echo "<label class=\"require\">Đáp án thứ " .($i+1). "</label> <input type='text' value='$noi_dung_dap_an[$i]' class ='form-control' required name='txt_dap_an[]'  />";
                        }
                        for($i = 1; $i<= 4; $i++){
                            if($this->view['data']['dap_an_dung']==$i){
                                $checked = 'checked';
                            }else{
                                $checked ='';
                            } 
                            echo $i ." <input type='radio' ".$checked." required style=\"margin-right:10px\" name='chk_dap_an_dung' value=".$i."  /> ";
                         }
                        
                        ?>
                        <div id ="box-dap-an" class="form-group"></div>
                        <div id ="box-dap-an-dung" class="form-group"></div>
                    </div> 
                    <div class="col-lg-12">
                        <div class="payment-adress mg-t-15 responsive-mg-t-0 mg-b-15">
                            <button type="submit" class="btn btn-primary waves-effect waves-light" title="Lưu" name="btnSave">Lưu</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
<script src="Public/Back-end/js/vendor/jquery-1.12.4.min.js"></script>
<script>
    var ma_mh=parseInt($('input[name="txt_ma_mon"]').val());
    function chon_hoc_phan(ma_mh){
        var _url = _base_url+'?controller=admin-question&action=list-hp&ma_mh=' + ma_mh;
        $.get( _url).done(function( data ) {
            var obj_json = JSON.parse(data);
            var option_str = '';
            $.each(obj_json,function (index, item) {
                option_str += '<option value="' + item.ma_hp + '">' + item.ten_hp + '</option>';
            });
            console.log(option_str);
            $('select[name="txt_ma_hp"]').html(option_str);
        });
    }
</script>