<?php
// echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($this->view);
// echo '</pre>';?>


    <div class="product-status mg-b-15 ">
            <div class="container-fluid">
                <div class="row">
                <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="breadcome-heading">
                                            
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <ul class="breadcome-menu">
                                            <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                            </li>
                                            <li><span class="bread-blod">Bài thi</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>     
        <div class="data-table-area mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <div class="main-sparkline13-hd mg-b-10">
                                    <h1>Tạo bài thi</h1>
                                    <div class="add-product ">
                                       
                                    </div>
                                </div>
                            </div>
                            <form action="" method="post">
                            <div class="sparkline13-graph product-status-wrap">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <div id="toolbar">
                                        <select class="form-control dt-tb">
											<option value="">Export Basic</option>
											<option value="all">Export All</option>
											<option value="selected">Export Selected</option>
										</select>
                                    </div>
                                    <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                        data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                        <thead>
                                            <tr>
                                                <th >Chọn đề thi</th>
                                                <th >Kỳ Thi</th>
                                                <th >Môn Học</th>
                                                <th >Số Lượng Câu Hỏi</th>
                                                <th >Tổng Điểm</th>
                                                <th >Người tạo</th>
                                                <th >Ngày tạo</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                        <?php
                                            if(isset($this->view['list'])){
                                                foreach(@$this->view['list'] as $row){
                                                    foreach($this->view['list_mh'] as $row1){
                                                        if($row['ma_mh']===$row1['ma_mh']){
                                                            $ten_mh = $row1['ten_mh'];
                                                        }
                                                    }
                                                    foreach($this->view['list_kt'] as $row2){
                                                        if($row['ma_kt']===$row2['id_kt']){
                                                            $ten_kt = $row2['ten_kt'];
                                                        }}

                                                    echo '<tr>
                                                        <td>
                                                            <input type="radio" name="id_dt" id="cid" value="'.$row['ma_dt'].'"> 
                                                        </td>
                                        
                                                        <td>'.$ten_kt.'</td>
                                                        <td>'.$ten_mh.'</td>
                                                        <td>'.$row['so_luong_cau_hoi'].'</td>
                                                        <td>'.$row['tong_diem'].'</td>
                                                        <td>'.$row['nguoitao'].'</td>
                                                        <td>'.$row['ngaytao'].'</td>
                                                    </tr>';

                                                }
                                            }
                                        ?>
                                       
                                        </tbody>
                                    </table>
                                    <div class="form-group">
                                        <label class=" require">Lớp</label>
                                        <select  name="txt_ma_lp" style="" class="form-control require">
                                            <?php
                                            $ma_lp = isset($_POST['txt_ma_lp'])?$_POST['txt_ma_lp']:'';
                                            if(isset($this->view['list_class'])){
                                                foreach ($this->view['list_class'] as $row){
                                                    echo '<option  value="'.$row['ma_lop'].'" >'.$row['ten_lop'].'</option>';
                                                }
                                            }
                                            ?>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        <label class="require"> Tổng số đề  </label>
                                        <input class="form-control" type="number" max="5" required name ="sl_bansao"/>
                                    </div>
                                    <input type="submit" style="margin:20px auto" name = "btnSave" value="Lưu" class="btn btn-primary waves-effect  waves-light">
                                    <p>
                                    <?php
                                    if(@$this->view['msg']!==null)
                                    if(is_array($this->view['msg']))
                                        foreach($this->view['msg'] as $row)
                                        echo $row.'<br />';
                                        
                                    ?></p>
                                </div>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>