<?php
// echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
// print_r($this->view);
// echo '</pre>';?>
<div class="clear"></div>
<div id="form_row" style="background: transparent;">
    <form action="" method="post">
    <div class="manager-nav">
            <h2>
                <i class="fas fa-book"></i> <a href="?controller=admin-kythi&action=list">Quản lý kỳ thi </a> 
                <span>
                    <?php
                    if(!empty($this->view['msg'])){
                        if(is_array($this->view['msg'])){
                             foreach ($this->view['msg'] as $item_msg)
                            echo '<b>'.$item_msg."</b>";
                        }else echo $this->view['msg'];
                    }
                    ?>
                </span>
                <span class="manager-item"><input type="image" src="Public/imgs/download.png" alt="SUBMIT" name="btnSave" />Lưu</span>
            </h2>
        </div>
        <fieldset>
            <legend>Thêm mới kỳ thi</legend>
            <div class="form_row">
                <label class="require">Tên kỳ thi</label>
                <input type="text" required class="form_input" name="txt_ten_kt" value="<?php echo isset($_POST['txt_ten_kt'])?$_POST['txt_ten_kt']:'' ;?>">
            </div>
            <div class="form_row">

                <label class="require">Bắt đầu</label>
                <input type="datetime-local" required class="form_input" name="time_start" id="" value="<?php echo isset($_POST['time_start'])?$_POST['time_start']:'' ;?>">
            </div>
            <div class="form_row">
                <label class="require">Kết thúc</label>
                <input type="datetime-local" required class="form_input" name="time_finish" id="" value="<?php echo isset($_POST['time_finish'])?$_POST['time_finish']:'' ;?>">
            </div>
        </fieldset>
    </form>
</div>




