<?php
// echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($this->view);
// echo '</pre>';?>


<div class="product-status mg-b-15 ">
            <div class="container-fluid">
                <div class="row">
                <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="breadcome-heading">
                                            
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <ul class="breadcome-menu">
                                            <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                            </li>
                                            <li><span class="bread-blod">Kỳ thi</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>     
        <div class="data-table-area mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <div class="main-sparkline13-hd mg-b-10">
                                    <h1>Danh sách kỳ thi</h1>
                                    <div class="add-product ">
                                        <a href="?controller=admin-kythi&action=add">Thêm </a>
                                    </div>
                                </div>
                            </div>
                            <div class="sparkline13-graph product-status-wrap">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <div id="toolbar">
                                        <select class="form-control dt-tb">
											<option value="">Export Basic</option>
											<option value="all">Export All</option>
											<option value="selected">Export Selected</option>
										</select>
                                    </div>
                                    <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                        data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                        <thead>
                                            <tr>
                                                <th>STT</th>
                                                <th  data-field="hp" data-editable="true">Tên kỳ thi</th>
                                                <th data-field="start" data-editable="true">Bắt đầu</th>
                                                <th data-field="start" data-editable="true">Kết thúc</th>
                                                <th>Status</th>
                                                <th data-field="action" >Cài Đặt</th> 
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $stt=0;
                                        
                                        foreach($this->view['list'] as $row){
                                            $link = '?controller=admin-kythi&action=edit&id='.$row['id_kt'];
                                            $link_delete = '?controller=admin-kythi&action=delete&id='.$row['id_kt'];
                                            if($row['locked']==1)
                                            {
                                                $img='<button class="ds-setting">Disabled</button>';
                                                $link_delete ='#';
                                            }
                                            if($row['locked']==0) {
                                                $img='<button class="pd-setting">Active</button>';
                                              

                                            }
                                            $stt++;                                      
                                            echo '<tr>
                                                <td>'.$stt.'</td>
                                                <td>'.$row['ten_kt'].'</td>
                                                <td>'.$row['thoi_gian_bat_dau'].'</td>
                                                <td>'.$row['thoi_gian_ket_thuc'].'</td>
                                                <td>'.$img.'</td>
                                                <td>
                                                    <a href='.$link.'><button data-toggle="tooltip" title="Sửa" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></a>
                                                    <a href='.$link_delete.'><button data-toggle="tooltip" title="Xóa" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button></a>
                                                </td>
                                            </tr>';
                                        }
                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>