<?php
/**
 * Created by ThaoNTT
 * User: Administrator
 * Date: 12/30/2017
 * Time: 3:31 PM
 */

//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//print_r($this->view);
//echo '</pre>';?>
<div class="center_content">


    <div id="right_wrap">
        <div id="right_content">
            <h2><?php echo $this->view['ten_lop']; ?></h2>


            <table id="rounded-corner">
                <thead>
                <tr>
                    <th>Mã Thí sinh</th>
                    <th>Họ và tên</th>
                    <th>Ngày sinh</th>
                    <th>Giới tính</th>
                    <th>Địa chỉ</th>
                    <th>Điện thoại</th>
                    <th>Sửa</th>
                    <th>Xóa</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <td colspan="12"></td>
                </tr>
                </tfoot>
                <tbody>
                <tr class="odd">


                    <?php
                    foreach($this->view['list'] as $row){

                        //?controller=admin-group&action=edit&id=14
                        $link = '?controller=admin-student&action=edit&id='.$row['ma_ts'];
                        $link_delete = '?controller=admin-student&action=delete&id='.$row['ma_ts'];
                        $gt;
                        if($row['gioi_tinh']==1) $gt="Nam";else $gt="Nữ";
                        echo '
                        <tr>
                            <td style="height: 50px;"><b>'.$row['ma_ts'].'</b></td>
                            <td style="height: 50px;"><a href="?controller=admin-class&action=thisinh&id='.$row['ma_ts'].'">'.$row['ho_dem'].' '.$row['ten'].'</a></td>
                            <td>'.substr($row['ngay_sinh'],0,10).'</td>
                            <td style="">'.$gt.'</td><td>'.$row['dia_chi'].'</td><td>'.$row['dien_thoai'].'</td>
                            <td><a href='.$link.'><img src="Public/backend/images/edit.png" alt="" title="" border="0" /></a></td>
                            <td><a href='.$link_delete.'><img src="Public/backend/images/trash.gif" alt="" title="" border="0" /></a></td>
                         </tr>';

                    }

                    ?>


                </tr>
                <tr><td colspan="10">
                        <?php

                        // hiển thị chỉ số trang của danh sách
                        if($this->view['total_pages']>1){?>

                        <div class="page-number">
                            <ul>
                                <?php
                                for($page = 1; $page <=$this->view['total_pages'];$page ++ ){
                                    echo '<li><a href="?controller=admin-class&action=class&id=3&page='.$page.'">'.$page.'</a></li>';
                                }
                                ?>
                                <?php }?>
                    </td></tr>
                </tbody>
            </table>




        </div>
    </div><!-- end of right content-->
    <!--        <div class="clear"></div>-->
    <!--        <div style="clear: both"></div>-->

    <div class="sidebar" id="sidebar">
        <h2>Danh sách </h2>

        <ul>
            <li><a href="?controller=admin-student&&action=list" >Thí sinh</a></li>
            <li><a href="?controller=admin-student&&action=listtk">Thí sinh & tài khoản</a></li>
        </ul>

        <h2>Help</h2>

        <ul>
            <li><a href="#">Help</a></li>
        </ul>

        <h2>Text Section</h2>
        <div class="sidebar_section_text">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>

    </div>


    <div class="clear"></div>
</div> <!--end of center_content-->
