

<?php
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($this->view);
//echo '</pre>';?>

<div class="clear"></div>
<div id="form_row">

    <form action="" method="post">
        <div class="manager-nav">
            <h2>
                <i class="fas fa-school"></i> <a href="?controller=admin-class&action=list">Quản lý lớp</a> 
                <span>
                    <?php
                    if(!empty($this->view['msg'])){
                        if(is_array($this->view['msg'])){
                             foreach ($this->view['msg'] as $item_msg)
                            echo '<b>'.$item_msg."</b>";
                        }else echo $this->view['msg'];
                    }
                    ?>
                </span>
                <span class="manager-item"><input type="image" src="Public/imgs/download.png" alt="SUBMIT" name="btnSave" />Lưu</span>
            </h2>
        </div>
        <div class="form_row"> 
            <?php
            if(isset($this->view['data'])){
                echo '<input type="hidden" name="ma_lop" value="'.$this->view['data']['ma_lop'].'">';
                echo '<h1>Chắc chắn xóa lớp: '.$this->view['data']['ten_lop'].'?</h1>';
            }
            ?>
        </div>
        
        <div class="form_row">
            <?php
            if(isset($this->view['data'])) {
                echo '<input type="submit" class="btn-delete" value="Đồng ý xóa" name="btnDelete" >';
                echo '<button class="btn-delete btn-return"><a href="?controller=admin-class&action=list">Trở về</a></button>';
            }
            ?>
        </div>

    </form>

</div>

