
<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
 ?>
  <div class="product-status mg-b-15 ">
    <div class="container-fluid">
        <div class="row">
        <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list single-page-breadcome">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="breadcome-heading">
                                    <span>
                                    <?php
                                    if(!empty($this->view['msg']['success'])){
                                    echo $this->view['msg']['success'];
                                    }
                                    ?>
                                    </span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <ul class="breadcome-menu">
                                    <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                    </li>
                                    <li><span class="bread-blod">Tài khoản</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
<div class="container-fluid">
    <div class="row">
        <h2 class="text-center">Sửa thông tin tài khoản</h2>
        <form action="" method="post" >
            <div class="col-xs-6 col-xs-offset-3 ">
                <div class="form-group">
                    <label class="require">Email</label>
                    <input type="email" required class="form-control" name="txt_email"  value="<?php echo isset($this->view['data']['email'])?$this->view['data']['email']:'' ;?>"/>
                    <div class="err">
                        <?php echo isset($this->view['msg']['mail'])? $this->view['msg']['mail']:''   ?>
                    </div>
                </div> 
               
                <div class="form-group">
                    <label class="require">Mật khẩu</label>
                    <input type="password" required class="form-control" name="txt_mat_khau" />
                    <div class="err">
                        <?php echo isset($this->view['msg']['mk1'])? $this->view['msg']['mk1']:''   ?>
                    </div>
                </div> 
                <div class="form-group">
                    <label class="require">Xác nhận mật khẩu</label>
                    <input type="password" required class="form-control" name="txt_mat_khau_2" />
                    <div class="err">
                        <?php echo isset($this->view['msg']['mk'])? $this->view['msg']['mk']:''   ?>
                    </div>
                </div> 
                
                
            </div>
            
            <div class="col-lg-12">
                <div class="payment-adress mg-t-15 responsive-mg-t-0 mg-b-15">
                    <button type="submit" class="btn btn-primary waves-effect waves-light" title="Lưu" name="btnSave">Lưu</button>
                </div>
            </div>
        </form>
    </div>
<div>
<!-- <div class="clear"></div>
<div id="form_row">
    <form action="" method="post">
    <div class="manager-nav">
            <h2>
                <i class="fas fa-users"></i> <a href="?controller=admin-user&action=list">Quản lý tài khoản</a> 
                <span>
                    <?php
                    if(!empty($this->view['msg']['success'])){
                     echo $this->view['msg']['success'];
                    }
                    ?>
                </span>
                <span class="manager-item"><input type="image" src="Public/imgs/download.png" alt="SUBMIT" name="btnSave" />Lưu</span>
            </h2>
        </div>
        <fieldset class="fieldset">
            <legend>Sửa thông tin tài khoản</legend>
             <div class="form_row">
                <label class="require">Email</label>
                <input type="email" required class="form-control" name="txt_email"  value="<?php echo isset($this->view['data']['email'])?$this->view['data']['email']:'' ;?>"/>
                <div class="err">
                    <?php echo isset($this->view['msg']['mail'])? $this->view['msg']['mail']:''   ?>
                </div>
            </div>  
            <div class="form_row">
                <label class="require">Mật khẩu</label>
                <input type="password" required class="form-control" name="txt_mat_khau" />
                <div class="err">
                    <?php echo isset($this->view['msg']['mk1'])? $this->view['msg']['mk1']:''   ?>
                </div>
            </div>
            <div class="form_row">
                <label class="require">Xác nhận mật khẩu</label>
                <input type="password" required class="form-control" name="txt_mat_khau_2" />
                <div class="err">
                    <?php echo isset($this->view['msg']['mk'])? $this->view['msg']['mk']:''   ?>
                </div>
            </div>
        </fieldset>
    </form>
</div> -->





