<?php

// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>
<div class="center_content">
    <div id="right_wrap">
        <div id="right_content">
        <h2><i class="fas fa-users"></i>Tài khoản<a href="?controller=admin-user&&action=add"><i class="fas fa-2x fa-plus-circle add-icon"> </i></a><a href="?controller=admin-user&&action=add"><span class="themmoi">Thêm Mới</span></a></h2>
            <table id="rounded-corner">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>Tên đăng nhập</th>
                    <th>Email</th>
                    <th>Nhóm tài khoản</th>
                    <th>Sửa</th><th>Xóa</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <td colspan="12"></td>
                </tr>
                </tfoot>
                <tbody>
                <tr class="odd">
                    <?php
                    if(!empty($this->view['list'])){
                    $stt = 0;
                    foreach($this->view['list'] as $row  ){
                        $stt ++;
                        $id = $row['id'];
                        $ten_dang_nhap = $row['username'];
                        $email = $row['email'];
                        foreach($this->view['group_acc'] as $group_name){
                            if($row['gid']===$group_name['gid'])$nhom = $group_name['name'] ;
                        }
                        
                        $link = '?controller=admin-user&action=edit&id='.$row['id'];
                        $link_delete = '?controller=admin-user&action=delete&id='.$row['id'];
                        echo '
                            <tr>
                                <td>'.$stt.'</td>
                                <td>'.$ten_dang_nhap.'</td>
                                <td>'.$email.'</td>
                                <td>'.$nhom .'</td>
                                <td><a href='.$link.'><img src="Public/backend/images/edit.png" alt="" title="" border="0" /></a></td>
                                <td><a href='.$link_delete.'><img src="Public/backend/images/trash.gif" alt="" title="" border="0" /></a></td>
                               
                            </tr>
                        ';
                    }}

                    ?>


                </tr>
                <tr><td colspan="10">
                        <?php
                        if($this->view['total_pages']>1){?>

                        <div class="page-number">
                            <ul>
                                <?php
                                for($page = 1; $page <=$this->view['total_pages'];$page ++ ){
                                    echo '<li><a href="?controller=admin-user&action=list&page='.$page.'">'.$page.'</a></li>';
                                }
                                ?>
                                <?php }?>
                    </td></tr>


                </tbody>
            </table>
        </div>
    </div>
    <div class="sidebar" id="sidebar">
        <h2>Quản lý tài khoản</h2>
        <ul>
            <li><a href="?controller=admin-group&&action=list" >Nhóm tài khoản</a></li>
            <li><a href="?controller=admin-teacher&&action=list">Giáo Viên</a></li>
            <li><a href="?controller=admin-student&&action=list">Học Sinh</a></li>
        </ul>


    </div>
    <div class="clear"></div>
</div> <!--end of center_content-->
