<?php

// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>
<div class="product-status mg-b-15 ">
    <div class="container-fluid">
        <div class="row">
        <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list single-page-breadcome">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="breadcome-heading">
                                    <span>
                                    <?php
                                    if(!empty($this->view['msg'])){
                                        if(is_array($this->view['msg'])){
                                            foreach ($this->view['msg'] as $item_msg)
                                            echo '<b>'.$item_msg."</b>";
                                        }else echo $this->view['msg'];
                                    }
                                    ?>
                                    </span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <ul class="breadcome-menu">
                                    <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                    </li>
                                    <li><span class="bread-blod">Tài khoản</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
<div class="data-table-area mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <div class="main-sparkline13-hd mg-b-10">
                                    <h1>Danh sách môn học</h1>
                                    <div class="add-product ">
                                        <a href="?controller=admin-user&action=add">Thêm </a>
                                    </div>
                                </div>
                            </div>
                            <div class="sparkline13-graph product-status-wrap">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <div id="toolbar">
                                        <select class="form-control dt-tb">
											<option value="">Xuất</option>
										</select>
                                    </div>
                                    <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                        data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                        <thead>
                                            <tr>
                                                <th>STT</th>
                                                <th>Tên đăng nhập</th>
                                                <th>Email</th>
                                                <th>Nhóm tài khoản</th>
                                                <th>Cài Đặt</th> 
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        if(!empty($this->view['list'])){
                                        $stt = 0;
                                        foreach($this->view['list'] as $row  ){
                                            $stt ++;
                                            $id = $row['id'];
                                            $ten_dang_nhap = $row['username'];
                                            $email = $row['email'];
                                            foreach($this->view['group_acc'] as $group_name){
                                                if($row['gid']===$group_name['gid'])$nhom = $group_name['name'] ;
                                            }
                                            
                                            $link = '?controller=admin-user&action=edit&id='.$row['id'];
                                            $link_delete = '?controller=admin-user&action=delete&id='.$row['id'];
                                            echo '
                                                <tr>
                                                    <td>'.$stt.'</td>
                                                    <td>'.$ten_dang_nhap.'</td>
                                                    <td>'.$email.'</td>
                                                    <td>'.$nhom .'</td>
                                                    <td>
                                                        <a href='.$link.'><button data-toggle="tooltip" title="Sửa" class="pd-setting-ed"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></a>
                                                        <a href='.$link_delete.'><button data-toggle="tooltip" title="Xóa" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button></a>
                                                    </td>
                                                </tr>
                                            ';
                                        }}

                                        ?>
                                       
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>


