<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>
<div class="clear"></div>
<div id="form_row">
    <form action="" method="post">
        <div class="manager-nav">
            <h2>
                <i class="fas fa-users"></i> <a href="?controller=admin-group&action=list">Quản lý nhóm </a> 
                <span>
                    <?php
                    if(!empty($this->view['msg'])){
                            echo $this->view['msg'];
                    }
                    ?>
                </span>
            </h2>
        </div>
        <div class="form_row">
            <input type="hidden" name="id_nhom" value="<?php echo  $this->view['data']['gid']; ?>">
            <h1 <?php echo isset($this->view['data'])?"":"hidden"; ?>>Chắc chắn xóa nhóm: <?php echo @$this->view['data']['name']; ?> ? </h1>
            
        </div>
        <div class="form_row">
            <?php
            if(isset($this->view['data'])) {
                echo '<input type="submit" class="btn-delete" value="Đồng ý xóa" name="btnDelete" >';
                echo '<button class="btn-delete btn-return"><a href="?controller=admin-group&action=list">Trở về</a></button>';
            }
            ?>
        </div>  
    </form>
</div>
