<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>
<div class="clear"></div>
<div id="form_row">
    <form action="" method="post">
        <div class="manager-nav">
            <h2>
                <i class="fas fa-users"></i> <a href="?controller=admin-group&action=list">Quản lý nhóm </a> 
                <span>
                    <?php
                    if(!empty($this->view['msg'])){
                        if(is_array($this->view['msg'])){
                             foreach ($this->view['msg'] as $item_msg)
                            echo '<b>'.$item_msg."</b>";
                        }else echo $this->view['msg'];
                    }
                    ?>
                </span>
                <span class="manager-item"><input type="image" src="Public/imgs/download.png" alt="Sửa nhóm" name="btnSave" />Lưu</span>
            </h2>
        </div>
        <fieldset>
            <legend>Sửa nhóm tài khoản</legend>
                <input type="hidden"  name="id_ten_nhom" value="<?php echo  $this->view['data']['gid']; ?>"  />
                <label for ="tennhom" class="require">Tên nhóm</label>
                <input type="text" required class="form_input" name="txt_ten_nhom" id="tennhom" value="<?php echo $this->view['data']['name'];?>" />
        </fieldset>
    </form>
</div>