<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>
 <div class="product-status mg-b-15 ">
    <div class="container-fluid">
        <div class="row">
        <div class="breadcome-area">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="breadcome-list single-page-breadcome">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <div class="breadcome-heading">
                                    <span>
                                    <?php
                                    if(!empty($this->view['msg'])){
                                        if(is_array($this->view['msg'])){
                                            foreach ($this->view['msg'] as $item_msg)
                                            echo '<b>'.$item_msg."</b>";
                                        }else echo $this->view['msg'];
                                    }
                                    ?>
                                    </span>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                <ul class="breadcome-menu">
                                    <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                    </li>
                                    <li><span class="bread-blod">Nhóm tài khoản</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
<div class="container-fluid">
    <div class="row">
        <h2 class="text-center">Sửa nhóm tài khoản</h2>
        <form action="" method="post" >
            <div class="col-xs-6 col-xs-offset-3 ">
                <div class="form-group">
                    <input type="hidden"  name="id_ten_nhom" value="<?php echo  $this->view['data']['gid']; ?>"  />
                    <label for ="tennhom" class="require">Tên nhóm</label>
                    <input type="text" required class="form-control" name="txt_ten_nhom" id="tennhom" value="<?php echo $this->view['data']['name'];?>" />
                </div> 
                
            </div>
            
            <div class="col-lg-12">
                <div class="payment-adress mg-t-15 responsive-mg-t-0 mg-b-15">
                    <button type="submit" class="btn btn-primary waves-effect waves-light" title="Lưu" name="btnSave">Lưu</button>
                </div>
            </div>
        </form>
    </div>
<div>

