
<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>
    <div class="product-status mg-b-15 ">
            <div class="container-fluid">
                <div class="row">
                <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="breadcome-heading">
                                       
                                            <span>
                                                <?php
                                                if(!empty($this->view['msg']['success'])){
                                                echo $this->view['msg']['success'];
                                                }
                                                ?>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <ul class="breadcome-menu">
                                            <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                            </li>
                                            <li><span class="bread-blod">Học sinh</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
     <div class="container-fluid">
    <div class="row">
        
        <form action="" method="post" >
            <div class="col-xs-6 col-xs-offset-3 text-center">
                <div class="form-group">
                <?php
                    if(isset($this->view['data'])){
                        echo '<input type="hidden" name="ma_thisinh" value="'.$this->view['data']['ma_ts'].'">';
                        echo '<h1>Chắc chắn xóa học sinh: '.$this->view['data']['ma_ts'].' ?</h1>';
                    }
                    ?>
                </div> 
                <div class="form-group">
                <?php
                if(isset($this->view['data'])) {
                    echo '<input type="submit" class="btn btn-danger mr10" value="Đồng ý xóa" name="btnDelete" >';
                    echo '<a href="?controller=admin-student&action=list"><p class="btn btn-primary">Trở về</p></a>';  
                }
                ?>   
                </div>
            </div>
        </form>
    </div>
<div>


