<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>

<div class="product-status mg-b-15 ">
            <div class="container-fluid">
                <div class="row">
                <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="breadcome-heading">
                                       
                                        <?php
                                        if(!empty($this->view['msg']['success'])){
                                        echo $this->view['msg']['success'];
                                        }
                                        ?>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <ul class="breadcome-menu">
                                            <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                            </li>
                                            <li><span class="bread-blod">Học sinh</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
      
<div class="container-fluid">
    <div class="row">
        <h2>Sửa học sinh</h2>
        <form action="" method="post" >
            <div class="col-xs-6">
                <div class="form-group">
                    <input hidden type="text"  name="txt_ma_ts" value="<?php echo$this->view['data']['ma_ts'];?>">
                    <input hidden type="text"  name="txt_ma_ts" value="<?php echo$this->view['data']['ma_ts'];?>">
                    <label class= "require">Mã lớp</label>
                    <select name="txt_ma_lp" class="form-control" >    
                        <?php
                        $ma_lp = isset($_POST['txt_ma_lp'])?$_POST['txt_ma_lp']:'';
                        if(isset($this->view['list_class'])){
                            foreach ($this->view['list_class'] as $row){
                                echo '<option  value="'.$row['ma_lop'].'" >'.$row['ten_lop'].'</option>';
                            }
                        }
                        ?>
                    </select>
                </div>     
                <div class="form-group">
                <label class= "require">Họ, Tên đệm</label>
                <input type="text" required class="form-control" name="txt_ho" value="<?php echo$this->view['data']['ho_dem'];?>">
                </div>

                <div class="form-group">
                    <label class= "require">Tên</label>
                    <input type="text" required class="form-control" name="txt_ten" value="<?php echo$this->view['data']['ten'];?>">        
                </div>
                <div class="form-group">
                    <label class= "require">Ngày sinh</label>
                    <input type="date" required class="form-control" name="txt_ns"value="<?php echo substr($this->view['data']['ngay_sinh'],0,10);?>" >
                </div>
                <div class="form-group">
                    <label class= "require">Giới tính</label>
                    <input type="radio" name="gt" value="0" checked>Nam<input type="radio" name="gt" value="1">Nữ
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    <label class= "require">Địa chỉ</label>
                    <input type="text" required class="form-control" name="txt_dc" value="<?php echo$this->view['data']['dia_chi'];?>" >

                </div>
                <div class="form-group">
                    <label class= "require">Điện thoại</label>
                    <input type="text" required class="form-control" name="txt_dt" value="<?php echo$this->view['data']['dien_thoai'];?>">
                    <div class="err small_err">
                        <?php echo isset($this->view['msg']['phone'])? $this->view['msg']['phone']:''   ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class= "require">Mật Khẩu</label>
                    <input type="password" required class="form-control" name="txt_passwd" >
                    <div class="err small_err">
                        <?php echo isset($this->view['msg']['pass'])? $this->view['msg']['pass']:''   ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class= "require">Email</label>
                    <input type="email" required class="form-control" name="txt_email"value="<?php echo isset($this->view['msg'][0]['email'])? $this->view['msg'][0]['email']:'' ?>">
                    <div class="err small_err">
                        <?php echo isset($this->view['msg']['mail'])? $this->view['msg']['mail']:''   ?>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="payment-adress mg-t-15 responsive-mg-t-0 mg-b-15">
                    <button type="submit" class="btn btn-primary waves-effect waves-light" title="Lưu" name="btnSave">Lưu</button>
                </div>
            </div>
               
        </form>
       
    </div>
</div>



