
<div class="container text-center" > 	
   <table class="table table-hover table-inverse  " style ="margin-top:30px">
		 <thead class="thead-inverse">
		 <tr><th colspan="5" class="bg-primary">Kết quả</th></tr>
			 <tr>
				<th>Mã thí sính</th>
				 <th>Mã bài thi</th>
				 <th>Số Câu Đúng</th>
				 <th>Ngày thi</th>
				 <th>Số Điểm</th>
			 </tr>
			 </thead>
			 <tbody>
				 <tr>
					 <td class="text-left"><?php echo isset($_SESSION['userLogin']['username'])? $_SESSION['userLogin']['username'] : 0; ?></td>
					 <td class="text-left"><?php echo isset($_SESSION['userLogin']['baithi']['mabaithi'])? $_SESSION['userLogin']['baithi']['mabaithi'] : 0; unset($_SESSION['userLogin']['baithi']['mabaithi'])  ?></td>
					 <td class="text-left"><?php echo isset($_SESSION['userLogin']['baithi']['so_cau_dung'])? $_SESSION['userLogin']['baithi']['so_cau_dung'] : 0; unset($_SESSION['userLogin']['baithi']['so_cau_dung'])  ?></td>
					 <td class="text-left"><?php echo isset($_SESSION['userLogin']['baithi']['ngaythi'])? $_SESSION['userLogin']['baithi']['ngaythi'] : 0; unset($_SESSION['userLogin']['baithi']['ngaythi'])  ?></td>
					 <td class="text-left" > <?php echo isset($_SESSION['userLogin']['baithi']['diem']) ?$_SESSION['userLogin']['baithi']['diem']:0; unset($_SESSION['userLogin']['baithi']['diem']) ?></td>
				 </tr>
				 
			 </tbody>
	 </table>
</div>
<div class="sidebar" id="sidebar">

        <input type="checkbox" id="menuTrigger"/>
        <div class="menu">
            <h3>Quản Lý </h3>
            <label for="menuTrigger" class="trigger">
            <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </label>
            <ul class="links">
                <li class="link"><a href="?controller=user-tests&action=list">Làm Bài Thi</a></li>
                <li class="link"><a href="?controller=user-tests&action=xemketqua">Xem Kết Quả</a></li>
                <li class="link"><a class="settings"href="?controller=user-tests&action=editpass">Đổi Mật Khẩu</a> </li>
            </ul>
        </div>
    </div>
<!-- //code không cho backlại trang -->
<script type="text/javascript">
	// history.pushState(null, null, location.href);
	// window.onpopstate = function () {
	// history.go(1);
};
</script>
 















