
<div class="container text-center" > 	
   <table class="table table-hover table-inverse mt-3 ">
		 <thead class="thead-inverse">
		 <tr><th colspan="2" class="bg-primary">Kết quả</th></tr>
			 <tr>
				 
				 <th>Số Câu Đúng</th>
				 <th>Số Điểm</th>
			 </tr>
			 </thead>
			 <tbody>
				 <tr>
					 <td><?php if(isset($_SESSION['so_cau_dung'])) echo $_SESSION['so_cau_dung'];  ?></td>
					 <td> <?php if(isset($_SESSION['diem'])) echo $_SESSION['diem'];  ?></td>
				 </tr>
				 
			 </tbody>
	 </table>
</div>
<!-- //code không cho load lại trang -->
<script type="text/javascript">
	history.pushState(null, null, location.href);
	window.onpopstate = function () {
	history.go(1);
};
</script>
 















