<div class="center_content">

    <div id="right_wrap">
        <div id="right_content" style="margin: 10px">
            <h2>Các bài thi đã hoàn thành</h2>
<!--            ma_bt ,baithi.ma_ts,thisinh.ho_dem,thisinh.ten,lop.ten_lop||
                [ma_bt] => 23,[ma_ts] => 1041360131.[ho_dem] => Nguyễ,[ten] => hà3,[ten_lop] => 12A2-->
            <table id="rounded-corner">
                <thead>
                    <tr>
                        <th>Mã Bài thi</th>
                        <th>Mã thí sinh</th>
                        <th>Họ Đệm</th>
                        <th>Tên</th>
                        <th>Lớp</th>
                        <th>Xem lại bài thi</th>
                    </tr>
                </thead>
                <tr>
                    <?php

                        foreach ($this->view['list'] as $row){
                            if($row['trang_thai']!=0){
                                echo "<tr>";
                                echo "
                                    <td>".$row['ma_bt']."</td>
                                    <td>".$row['ma_ts']."</td>
                                    <td>".$row['ho_dem']."</td>
                                    <td>".$row['ten']."</td>
                                    <td>".$row['ten_lop']."</td>
                                ";
                                $link = '?controller=user-tests&action=xembai&ma_bt='.$row['ma_bt'];
                                    echo "
                                        <td>
                                            <a href='.$link.'>
                                                <img src='Public/backend/images/Document-icon.png' alt='' title='' style='width: 20px;' border='0' />
                                            </a>
                                        </td>
                                    ";
                                echo "<tr>";
                            }
                        }

                    ?>



                <tr>
                    <td colspan="11">
                        <?php
                        // hiển thị chỉ số trang của danh sách
                        if($this->view['total_pages']>1){?>
                        <div class="page-number">
                            <ul>
                                <?php
                                for($page = 1; $page <=$this->view['total_pages'];$page++ ){
                                    echo '<li><a href="?controller=user-tests&action=list&page='.$page.'">'.$page.'</a></li>';
                                }
                                ?>
                            <?php }?>
                    </td>
                </tr>
            </table>






        </div>
    </div>


    <div class="clear"></div>
</div> <!--end of center_content-->
