<?php

//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//print_r($this->view);
//echo '</pre>';?>
<div class="clear"></div>
<div class="center_content">
    <div id="right_wrap">
        <div id="right_content" >
            <form action="" method="post">
            <fieldset>
                <legend>Đổi Mật Khẩu</legend>
                <div class="form_row">
                    <label>Tên đăng nhập</label>
                    <input type="text" disabled class="form_input" name="username" value="<?php echo $_SESSION['userLogin']['username'] ;?>">
                </div>
                <div class="form_row">
                    <label class ="require">Mật Khẩu Cũ</label>
                    <input required type="password" class="form_input" name="mk_cu" value="<?php isset($_POST['mk_cu'])?$_POST['mk_cu']:'' ?>" />
                </div>
                <div class="form_row">
                    <label class ="require">Nhập khẩu Mới</label>
                    <input required type="password" class="form_input" name="mk_1" />
                </div>
                <div class="form_row">
                    <label class ="require">Nhập Lại Mật khẩu Mới</label>
                    <input required type="password" class="form_input" name="mk_2" />
                </div>
                <div class="form_row">
                    <input type="submit" class="form_submit" value="Đổi Mật Khẩu" name="btnSave" />
        <!--            --><?php
                    if(!empty($this->view['msg'])){
                        //foreach ($this->view['msg'] as $msg)
                            echo '<b>'.$this->view['msg']."</b><br>";
                    }
        //            ?>
                </div>
            
                

            </fieldset>
            </form>
        </div>
    </div>

    <div class="sidebar" id="sidebar">

        <input type="checkbox" id="menuTrigger"/>
        <div class="menu">
            <h3>Quản Lý </h3>
            <label for="menuTrigger" class="trigger">
            <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </label>
            <ul class="links">
                <li class="link"><a href="?controller=user-tests&action=list">Làm Bài Thi</a></li>
                <li class="link"><a href="?controller=user-tests&action=xemketqua">Xem Kết Quả</a></li>
                <li class="link"><a class="settings"href="?controller=user-tests&action=editpass">Đổi Mật Khẩu</a> </li>
            </ul>
        </div>
        <div class="css-script-ads">

            <div class="clear"></div>
        </div>
    </div>
</div>





