<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>
        <div class="container">
        <div class="col-lg-8 d-block m-auto bg-light quizsetting ">
            <div class="card">
                <p class="card-header text-center " ><span class="text-uppercase text-primary"> <?php echo $_SESSION['userLogin']['username']; ?></span>, Chọn phương án trả lời đúng. <i class="fas fa-thumbs-up"></i>	 </p>
            </div>
            
            <form action="" method="post" id="myForm">
            <input type="hidden"  name="ma_bt"  id="" value = <?php echo $_GET['ma_bt']?>>
            <input type="hidden"  name="total_question"  id="total_question" value = <?php echo $this->view['count_question']?>>
                <div class="card">
                
                    
                    <?php 
                    $i = 0;
                    //strip_tags : bỏ tag thẻ p lấy từ CSDL
                        foreach($this->view['ds_ch'] as $row)
                        {
                    echo '<p class="card-header bg-info">';
                            
                        foreach($row as $val)$i++;
                        echo  $i.'.'.strip_tags($val['noi_dung_ch']);
                            $answer_serialize = unserialize($val['noi_dung_dap_an']);
                            foreach($answer_serialize as $stt => $ans){
                                echo '<div class = "card-block"><label class = "container" id="edit-padding">'.$ans[0];
                                echo '<input type = "radio" class="custom-control-input" id ="'.$val['ma_ch'].$stt.'" name ="ch'.$val['ma_ch'].'" value="'.$stt.'">';
                                echo ' <span class="checkmark"></span>';
                                echo '</label></div>';
                            }
                    } //end of foreach row
                            
                        
                    ?>    
                    
                </div>              
                <button type="submit" class="btn btn-secondary mg-submit" id="btnSave" name = "btnSave" value="Hoàn Thành Bài Thi" onclick="return hoanthanh()">Nộp Bài Thi</button>
                
            </form>
        </div>  
    </div>
<div class="center_content" style="padding-left: 50px;padding-top: 20px;" onload="start()">
    <div style="position: fixed;right: 0;top: 0; padding: 20px; background-color: #eee; border: 1px solid #ccc; border-radius: 5px;" <?php if($this->view['locked']==1) echo "hidden" ?> >
        <span id="h">Giờ</span> :
        <span id="m">Phút</span> :
        <span id="s">Giây</span>
    </div>
</div>
    <script type="text/javascript">
 $(window).bind('beforeunload', function(e) { 
    return "Unloading this page may lose data. What do you want to do..."
    e.preventDefault();
});
     var h = null; // Giờ
        var m = null; // Phút
        var s = null; // Giây
        var timeout = null; // Timeout
        var validate =false;
        window.onload = function start()
        {
            /*BƯỚC 1: LẤY GIÁ TRỊ BAN ĐẦU*/
            if (h === null)
            {
                var time=
                <?php
                if (isset($this->view['pick_time']))
                
                   echo "parseInt(".$this->view['pick_time'].");";
                    
                else
                    echo "null;";
                ?>

                if(time==null){
                    h =null;
                    m =null;
                    s =null;
                }
                else{
                    h = parseInt(time/60); // Giờ
                    m = parseInt(time%60);
                    s = parseInt(time-parseInt(time));
                }
            }
            /*BƯỚC 1: CHUYỂN ĐỔI DỮ LIỆU*/
            // Nếu số giây = -1 tức là đã chạy ngược hết số giây, lúc này:
            //  - giảm số phút xuống 1 đơn vị
            //  - thiết lập số giây lại 59
            if (s === -1){
                m -= 1;
                s = 59;
            }

            // Nếu số phút = -1 tức là đã chạy ngược hết số phút, lúc này:
            //  - giảm số giờ xuống 1 đơn vị
            //  - thiết lập số phút lại 59
            if (m === -1){
                h -= 1;
                m = 59;
            }

            // Nếu số s = -1 tức là đã hết giờ, lúc này:
            //  - Dừng chương trình
            if (h == -1){
                clearTimeout(timeout);
                
                validate = true;
                
                document.getElementById('btnSave').click();
                
               
            }

            /*BƯỚC 1: HIỂN THỊ ĐỒNG HỒ*/
            document.getElementById('h').innerText = h.toString();
            document.getElementById('m').innerText = m.toString();
            document.getElementById('s').innerText = s.toString();

            /* GIẢM PHÚT XUỐNG 1 GIÂY VÀ GỌI LẠI SAU 1 GIÂY */
            timeout = setTimeout(function(){
                s--;
               start();
            }, 1000);
        }

   function hoanthanh() {
           if(validate==false){
               var x= confirm("Bạn Chắc chắn muốn hoàn thành bài thi?");
               if(x){
                   // Xử lý bỏ trống câu trả lời
                   let total_question =$('#total_question').val();
                   let count_check=0;
                   count_check= $(':radio[name^="ch"]:checked').length;
                   if(total_question!=count_check)  {
                       alert("Không được bỏ trống câu trả lời");
                      
                       return false;
                   }else{
                       return true;
                   }
   
               }
                return false;
           }else{
               return true;
           }
           
 
       }
 
</script>


