<div class="center_content">

    <div id="right_wrap">
        <div id="right_content" >
            <h2>Các bài thi chưa làm</h2>
            <table id="rounded-corner">
                <thead>
                    <tr>
                        <th>Mã Bài thi</th>
                        <th>Ngày Thi</th>
                        <th>Đã Hoàn Thành</th>
                        <th>Làm Bài</th>
                    </tr>
                </thead>
                <tr>
                    <?php

                        foreach ($this->view['list'] as $row){
                            echo "<tr>";
                            echo '
                                <td >'.$row['ma_bt'].'</td>
                                <td >'.$row['ngay_thi'].'</td>
                                
                                <td >'.($row['trang_thai']==1?"Hoàn thành":"Chưa hoàn thành").'</td>
                                
                            ';
                            $link = '?controller=user-tests&action=lambai&ma_ts='.$row['ma_ts'].'&ma_bt='.$row['ma_bt'];
                           if($row['trang_thai']!=1){
                                echo '<td><a href='.$link.'><img src="Public/backend/images/edit.png"/></a></td>';
                           }else{
                            echo '<td><img width="40px" src="Public/backend/images/none.jpg"/></td>';
                           }
                            echo "<tr>";
                        }

                    ?>



                <tr>
                    <td colspan="11">
                        <?php
                        // hiển thị chỉ số trang của danh sách
                        if($this->view['total_pages']>1){?>
                        <div class="page-number">
                            <ul>
                                <?php
                                for($page = 1; $page <=$this->view['total_pages'];$page++ ){
                                    echo '<li><a href="?controller=user-tests&action=list&page='.$page.'">'.$page.'</a></li>';
                                }
                                ?>
                            <?php }?>
                    </td>
                </tr>
            </table>






        </div>
    </div>
    <div class="sidebar" id="sidebar">

        <input type="checkbox" id="menuTrigger"/>
        <div class="menu">
            <h3>Quản Lý </h3>
            <label for="menuTrigger" class="trigger">
            <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </label>
            <ul class="links">
                <li class="link"><a href="?controller=user-tests&action=list">Làm Bài Thi</a></li>
                <li class="link"><a href="?controller=user-tests&action=xemketqua">Xem Kết Quả</a></li>
                <li class="link"><a class="settings"href="?controller=user-tests&action=editpass">Đổi Mật Khẩu</a> </li>
            </ul>
        </div>
        <div class="css-script-ads">
       
            <div class="clear"></div>
        </div>
    </div>
</div>

