
<div class="row">

    <div class="col-xs-12" style ="width:90% ;margin-left:170px">
       
            <h3>Các bài thi </h3>
            <table id="rounded-corner" style ="width:100% " >
                <thead>
                    <tr>
                        <th>Mã Bài thi</th>
                        <th>Ngày Thi</th>
                        <th>Trạng thái</th>
                        <th>Làm Bài</th>
                    </tr>
                </thead>
                <tr>
                    <?php

                        foreach ($this->view['list'] as $row){
                            echo "<tr>";
                            echo '
                                <td >'.$row['ma_bt'].'</td>
                                <td >'.$row['ngay_thi'].'</td>
                                
                                <td >'.($row['trang_thai']==1?"Hoàn thành":"Chưa hoàn thành").'</td>
                                
                            ';
                            $link = '?controller=user-tests&action=lambai&ma_ts='.$row['ma_ts'].'&ma_bt='.$row['ma_bt'];
                           if($row['trang_thai']!=1){
                                echo '<td><a href='.$link.'><img src="Public/backend/images/edit.png"/></a></td>';
                           }else{
                            echo '<td><img width="16px" src="Public/backend/images/none.jpg"/></td>';
                           }
                            echo "<tr>";
                        }

                    ?>



                <tr>
                    
                </tr>
            </table>






        </div>
    </div>
    <div class="sidebar" id="sidebar">

        <input type="checkbox" id="menuTrigger"/>
        <div class="menu">
            <!-- <h3>Quản Lý </h3> -->
            <label for="menuTrigger" class="trigger">
            <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </label>
            <ul class="links">
                <li class="link"><a href="?controller=user-tests&action=list">Làm Bài Thi</a></li>
                <li class="link"><a href="?controller=user-tests&action=xemketqua">Xem Kết Quả</a></li>
                <li class="link"><a class="settings"href="?controller=user-tests&action=editpass">Đổi Mật Khẩu</a> </li>
            </ul>
        </div>
      
       
            <div class="clear"></div>
        </div>
    </div>
</div>

