
<div class="center_content" style="padding-left: 50px;padding-top: 20px;" >
    <form action="" method="post" method="post" name="dateForm" id="dateForm">
        <?php

        $dem=1;
        $So_Cau_Dung=0;
        $noi_dung_dap_an=$this->view['noi_dung_dap_an'];//
        $ds_dap_an=$this->view['list_as'];//danh sách đáp án của thí sinh

        foreach ($this->view['list_qs'] as $row) {//Duyệt số lượng câu hỏi trong đề thi
            $UserTestsModel = new UserTestsModel();
            $arrx = $UserTestsModel->Lay_CH($row);//Lấy mảng thông tin về câu hỏi
            $return_data = unserialize($arrx['noi_dung_dap_an']);//lấy nội dung đáp án bằng hàm chuyển chuỗi về mảng
            $nd_ch=$arrx['noi_dung_ch'];
            echo "<span style='font-weight: bold;font-size: 16px;'>Câu hỏi ". $dem ."  </span>:<span style='font-weight: bold'> ".$nd_ch." </span>";// in ra nội dung câu hỏi

            $stt = 1;
            foreach ($return_data as $row2) {
                $dapan=$noi_dung_dap_an[$row][$stt-1];//lấy đáp án của thí sinh
                if($return_data[$stt][1]==1){//in ra câu trả lời đúng của câu hỏi
                    echo '<p style="color: green;font-weight: bold">' .$stt.', '. $row2[0] ;
                    if($return_data[$stt][1]==$dapan){// nếu câu hỏi trùng với đáp án
                        $So_Cau_Dung++;
                        echo ' (+1)</p>';
                    }else echo '</p>';
                }
                else{//in ra các đáp án sai
                    if($ds_dap_an[$row]==($stt-1)){//nếu đáp án của thí sinh bằng đáp án sai
                        echo '<p style="color: red;font-weight: bold">' .$stt.', '. $row2[0] . '</p>';
                    }
                    else//nếu thí sinh không có đáp án đưa ra
                    echo '<p>' .$stt.', '. $row2[0] . '</p>';
                }
                $stt++;
            }
            $dem++;
            echo "<br>";
        }
        ?>
        <div style="width: 100%; text-align: center;font-size: 20px;">
        <?php
        echo "<br> số Lượng Câu hỏi Đúng: ".$So_Cau_Dung;
        echo "<br> số Lượng Câu hỏi: ".$this->view['So_Cau_hoi'];
        echo "<br> số Điểm đạt được: ".(($So_Cau_Dung/$this->view['So_Cau_hoi'])*10)."<br>";
        ?>
        </div>
        <label for=""></label>
        <div class="form_row">
            <?php
            if($this->view['locked']==0)
            echo '<input type="submit" class="form_submit"value="Hoàn Thành Bài Thi" onclick="return hoanthanh()" name="btnSave" id="btnSave" />';
            ?>
        </div>
    </form>

</div>


