<div class="row">
<div class="col-xs-12" style ="width:90% ;margin-left:170px">
       
            <h2>Kết Quả</h2>
            <table id="rounded-corner" style ="width:100% " >
             
                <thead>
                    <tr>
                        <th>Mã Bài thi</th>
                        <th>Ngày Thi</th>
                        <th>Số Câu Đúng</th>
                        <th>Điểm</th>
                    </tr>
                </thead>
               
                <tr>
                <?php
                    foreach ($this->view['list'] as $row){
                        if($row['trang_thai']!=0){
                            echo "<tr>";
                            echo "
                                <td>".$row['ma_bt']."</td>
                                <td>".$row['ngay_thi']."</td>
                                <td>".$row['so_cau_dung']."</td>
                                <td>".$row['diem']."</td>
                            
                            ";
                            
                        }
                    }
                    ?>
                <tr>
                    
                </tr>
            </table>
        </div>
    </div>
    </div>
    <div class="sidebar" id="sidebar">
        <input type="checkbox" id="menuTrigger"/>
        <div class="menu" style="top: 86px;">
          
            <label for="menuTrigger" class="trigger">
            <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </label>
            <ul class="links">
                <li class="link"><a href="?controller=user-tests&action=list">Làm Bài Thi</a></li>
                <li class="link"><a href="?controller=user-tests&action=xemketqua">Xem Kết Quả</a></li>
                <li class="link"><a class="settings"href="?controller=user-tests&action=editpass">Đổi Mật Khẩu</a> </li>
            </ul>
        </div>
    </div>
    <div class="clear"></div>
</div> <!--end of center_content-->
