<?php
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//print_r($this->view);
//echo '</pre>';?>
<div class="clear"></div>
<div id="form_row">
    <form action="" method="post">
        <div class="form_row">
            <h2 id="h2">Sửa Đề Thi</h2>
            ma_dt,ma_kt,ma_mh,so_luong_cau_hoi,ds_id_ch,tong_diem Tăng dần 1,thoi_gian_lam_bai,locked
            <label>ID Kỳ Thi</label>
            <input disabled type="text" class="form_input" name="id_kt"  value="<?php echo$this->view['data']['id_kt'];  ?>" />
        </div>
        <div class="form_row">

            <label>Môn Học</label>
            <input disabled type="text" class="form_input" name="txt_ma_dt" value="<?php ?>" />
        </div>

        <div class="form_row">
            <label>Số Lượng Câu Hỏi</label>
            <input type="datetime-local" class="form_input" name="txt_so_luong_cau_hoi" />
        </div>
        <div class="form_row">
            <label>Tổng Điểm</label>
            <input type="datetime-local" class="form_input" name="txt_tong_diem" />
        </div>


        <!--////-->

        <!--        <div class="form_row">-->
        <!--<label>Email:</label>-->
        <!--<input type="text" class="form_input" name="" />-->
        <!--</div>-->
        <!---->
        <!--<div class="form_row">-->
        <!--<label>Subject:</label>-->
        <!--<select class="form_select" name="">-->
        <!--<option>Select one</option>-->
        <!--</select>-->
        <!--</div>-->
        <!---->
        <!--<div class="form_row">-->
        <!--<label>Message:</label>-->
        <!--<textarea class="form_textarea" name=""></textarea>-->
        <!--</div>-->
        <div class="form_row">
            <input type="submit" class="form_submit" value="Sửa nhóm" name="btnSave" />
            <?php
            if(!empty($this->view['msg'])){
                foreach ($this->view['msg'] as $item_msg)
                    echo '<b>'.$item_msg."</b>";
            }
            ?>
        </div>
    </form>
</div>