<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>


<div class="product-status mg-b-15 ">
            <div class="container-fluid">
                <div class="row">
                <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="breadcome-list single-page-breadcome">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <div class="breadcome-heading">
                                            
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                        <ul class="breadcome-menu">
                                            <li><a href="#">Home</a> <span class="bread-slash">/</span>
                                            </li>
                                            <li><span class="bread-blod">Đề thi</span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>     
        <div class="data-table-area mg-b-15">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="sparkline13-list">
                            <div class="sparkline13-hd">
                                <div class="main-sparkline13-hd mg-b-10">
                                    <h1>Danh sách đề thi</h1>
                                    <div class="add-product ">
                                        <a href="?controller=admin-exam&action=add">Thêm </a>
                                    </div>
                                </div>
                            </div>
                            <div class="sparkline13-graph product-status-wrap">
                                <div class="datatable-dashv1-list custom-datatable-overright">
                                    <div id="toolbar">
                                        <select class="form-control dt-tb">
											<option value="">Export Basic</option>
											<option value="all">Export All</option>
											<option value="selected">Export Selected</option>
										</select>
                                    </div>
                                    <table id="table" data-toggle="table" data-pagination="true" data-search="true" data-show-columns="true" data-show-pagination-switch="true" data-show-refresh="true" data-key-events="true" data-show-toggle="true" data-resizable="true" data-cookie="true"
                                        data-cookie-id-table="saveId" data-show-export="true" data-click-to-select="true" data-toolbar="#toolbar">
                                        <thead>
                                            <tr>
                                                <th data-field="kythi" data-editable="true">Kỳ Thi</th>
                                                <th data-field="mon" data-editable="true">Môn học</th>
                                                <th data-field="sl" data-editable="true">Số lượng câu hỏi</th>
                                                <th data-field="tong" data-editable="true">Tổng Điểm</th>
                                                <th data-field="thoigian" data-editable="true">Thời Gian làm bài</th>
                                                <th>Status</th>
                                                <th data-field="action" >Cài Đặt</th> 
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                      
                                        $img_delete='';
                                        $img_edit='<img src="Public/backend/images/edit.png" />';
                                        if(isset($this->view['list'])){
                                            foreach($this->view['list'] as $row){
                                                $link = '?controller=admin-exam&action=edit&id='.$row['ma_dt'];
                                                $link_delete = '?controller=admin-exam&action=delete&id='.$row['ma_dt'];
                                                if($row['locked']==1){
                                                    $img='<button class="ds-setting">Disabled</button>';
                                                   
                                                    $link_delete ='#';
                                                }
                                                if($row['locked']==0) {
                                                  
                                                    $img='<button class="pd-setting">Active</button>';
                                                   
                                                }
                                                foreach($this->view['list_mh'] as $row1){
                                                    if($row['ma_mh']===$row1['ma_mh']){
                                                        $ten_mh = $row1['ten_mh'];
                                                    }
                                                }
                                                foreach($this->view['list_kt'] as $row2){
                                                    if($row['ma_kt']===$row2['id_kt']){
                                                        $ten_kt = $row2['ten_kt'];
                                                    }}

                                                echo '
                                                <tr>
                                                    
                                                    <td>'.$ten_kt.'</td>
                                                    <td>'.$ten_mh.'</td>
                                                    <td>'.$row['so_luong_cau_hoi'].'</td>
                                                    <td>'.$row['tong_diem'].'</td>
                                                    <td>'.$row['thoi_gian_lam_bai'].'</td>
                                                    <td>'.$img.'</td>
                                                    <td><a href='.$link_delete.'><button data-toggle="tooltip" title="Xóa" class="pd-setting-ed"><i class="fa fa-trash-o" aria-hidden="true"></i></button></a></td>
                                                </tr>';
                                            }
                                        }

                                        ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
