<?php
// echo '<pre>';
// print_r($this->view);
// echo '</pre>';
?>
<div class="center_content">

    <div id="right_wrap">
        <div id="right_content" style="margin:10px">
            <h2>Kết Quả</h2>

            <table id="rounded-corner">
                <thead>
                    <tr>

                        <th>Mã Bài thi</th> 
                        <th>Mã thí sinh</th>
                        <th>Số Câu Đúng</th>
                        <th>Điểm</th>
                        <th>Kỳ thi</th>
                        <th>Ngày Thi</th>
                     
                    </tr>
                </thead>
                <tr>
                    <?php

                        foreach ($this->view['list'] as $row){
                            
                                echo "<tr>";
                                echo "
                                <td>".$row['ma_bt']."</td>
                                <td>".$row['ma_ts']."</td>
                                <td>".$row['so_cau_dung']."</td>
                                <td>".$row['diem']."</td>
                                <td>".$row['ten_kt']."</td>
                                <td>".$row['ngay_thi']."</td>
                                
                                   
                                ";
                                
                            
                        }

                    ?>



                
            </table>
        </div>
    </div>
    <!-- <div class="sidebar" id="sidebar">

        <input type="checkbox" id="menuTrigger"/>
        <div class="menu">
            <h3>Quản Lý </h3>
            <label for="menuTrigger" class="trigger">
            <div class="line"></div>
                <div class="line"></div>
                <div class="line"></div>
            </label>
            <ul class="links">
                <li class="link"><a href="?controller=user-tests&action=list">Làm Bài Thi</a></li>
                <li class="link"><a href="?controller=user-tests&action=xemketqua">Xem Kết Quả</a></li>
            </ul>
        </div>
    </div> -->


    <div class="clear"></div>
</div> <!--end of center_content-->
