
<div class="clear"></div>
<div id="form_row">
<form action="" method="post">
<div class="manager-nav">
            <h2>
                <i class="fas fa-book"></i> <a href="?controller=admin-subject&action=list">Quản lý câu hỏi </a> 
                <span>
                    <?php
                    if(!empty($this->view['msg'])){
                            echo $this->view['msg'];
                    }
                    ?>
                </span>
            </h2>
        </div>
    <div class="form_row">
                <input type="hidden" name="ma_ch" value="<?php echo $this->view['data']['ma_ch']?>">
                <h1>Chắc chắn xóa Câu hỏi ? </h1>;
        
    </div>
        <div class="form_row">
            <?php
 
        if(isset($this->view['data'])) {
            echo '<input type="submit" class="btn-delete" value="Đồng ý xóa" name="btnDelete" >';
            echo '<button class="btn-delete btn-return"><a href="?controller=admin-question&action=list">Trở về</a></button>';
        }
        ?>
        </div>

</form>

</div>
