<?php
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//print_r($this->view);
//echo '</pre>';?>
<div class="clear"></div>
<div id="form_row">
    <form action="" method="post">
        <div class="form_row">
            <h2 id="h2">Thêm đề thi</h2>

            <label>Kỳ thi</label>
            <select class="form_input" name="txt_ma_kt" ">
                <?php
                if(isset($this->view['list_exam'])){
                    foreach ($this->view['list_exam'] as $row){

                        echo '<option  value="'.$row['id_kt'].'" >'.$row['ten_kt'].'</option>';
                    }
                }
                ?>
                ?>
            </select>
        </div>

        <div class="form_row">
            <label>Môn học</label>
            <select name="txt_ma_mon" class="form_input" onchange ="chon_hoc_phan(this.value)">
                <?php
                $ma_mh = isset($this->view['data']['ma_mh'])?$this->view['data']['ma_mh']:'';
                if(isset($this->view['list_sub_group'])){
                    foreach ($this->view['list_sub_group'] as $row){
                        if($row['ma_mh'] ==  $ma_mh)
                            $selected = ' selected ';
                        else
                            $selected ='';

                        echo '<option '.$selected.' value="'.$row['ma_mh'].'" >'.$row['ten_mh'].'</option>';
                    }
                }
                ?>
                ?>
            </select>
        </div>
        <div class="form_row">
            <label>Số lượng câu hỏi </label>
            <input type="number" name="txt_sl"  class="form_input" id="txt_so_luong_cau_hoi" name="txt_so_luong_cau_hoi" value="0">
        </div>
        <div class="form_row">
            <label>Câu hỏi </label>
            <input type="text" name="txt_cau_hoi" id="txt_cau_hoi"  class="form_input" readonly>
            <span id="btn_brows_question" style="cursor: pointer;color:red;font-weight: bolder" >Chọn câu hỏi...</span>
        </div>
        <div class="form_row">
            <label>Tổng điểm </label>
            <input type="text" class="form_input" name="txt_tong_diem" " />
        </div>
        <div class="form_row">
            <label>Thời gian làm bài(phút) </label>
            <input type="text" class="form_input" name="txt_tg" " />
        </div>

        <div class="form_row">
            <input type="submit" class="form_submit" value="Thêm đề thi" name="btnSave" />
            <?php
            if(!empty($this->view['msg'])){
                if(is_array($this->view['msg']))
                foreach ($this->view['msg'] as $row)
                 echo '<b>'.$row."</b>";
                else
                    echo '<b>'.$this->view['msg']."</b>";
            }
            ?>
        </div>
    </form>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="Public/backend/js/choncauhoi.js">

</script>
