<?php
/**
 * Created by ThaoNTT
 * User: Administrator
 * Date: 1/13/2018
 * Time: 10:58 PM
 */

// echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//     print_r($this->view);
// echo '</pre>';?>
<div id="form_row">

    <form action="" method="post">
        <div class="form_row">
            <h2 id="h2">Xóa đề thi</h2>
            <input type="hidden" name="id_dt" value="<?php echo(@$this->view['data']['ma_dt']);?>">
            <h1 <?php echo isset($this->view['data'])?"":"hidden"; ?> >Chắc chắn xóa đề: <?php echo @$this->view['data']['ma_dt']; ?> ? </h1>
        </div>
        <div class="form_row">
         <input type="submit" class="form_submit" value="Đồng ý xóa" name="btnDelete" />
            <?php
            if(!empty($this->view['msg'])){
                $msg1=  new func();
                $msg1->message($this->view['msg']);
            }

            ?>
        </div>

    </form>

</div>
