<?php

$mang_cong=array();
$mang_cong=unserialize($this->view['data']['ds_id_ch']);

//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($mang_cong);
//echo '</pre>';
$xxx="";
for($i = 0;$i<count($mang_cong);$i++){
    if ($i!=(count($mang_cong)-1)){
        $xxx.=$mang_cong[$i].',';
    }
    else {
        $xxx .= $mang_cong[$i];
    }
}
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')<br>';
//	print_r($xxx);
//echo '</pre>';


?>
<div class="clear"></div>
<div id="form_row">
    <form action="" method="post">
        <div class="form_row">
            <h2 id="h2">Sửa đề thi</h2>
            <label>Kỳ thi</label>
            <input type="text" readonly class="form_input" name ="txt_kt" value="<?php
            if(isset($this->view['list_exam'])){
                $x=$this->view['data']['ma_kt'];
                foreach ($this->view['list_exam'] as $row){
                    if($row['id_kt']== $x) echo $row['ten_kt'];
                }
            }
            ?>">
        </div>

        <div class="form_row">
            <label>Môn học</label>
<!--            <input type="text" readonly class="form_input" name ="txt_mh" value="--><?php
//            if(isset($this->view['list_sub_group'])){
//                $x=$this->view['data']['ma_mh'];
//                foreach ($this->view['list_sub_group'] as $row){
//                    if($row['ma_mh']== $x) echo $row['ten_mh'];
//                }
//            }

            ?><!--">-->
            <select name="txt_ma_mon" class="form_input" onchange ="chon_hoc_phan(this.value)">
                <?php
                $ma_mh = isset($this->view['data']['ma_mh'])?$this->view['data']['ma_mh']:'';
                if(isset($this->view['list_sub_group'])){
                    foreach ($this->view['list_sub_group'] as $row){
                        if($row['ma_mh'] ==  $ma_mh)
                            $selected = ' selected ';
                        else
                            $selected ='';

                        echo '<option '.$selected.' value="'.$row['ma_mh'].'" >'.$row['ten_mh'].'</option>';
                    }
                }
                ?>
                ?>
            </select>

        </div>
        <input type="text" name="txt_ma_kt" value="<?php echo @$this->view['data']['ma_kt']?>" class="form_input" hidden>
        <div class="form_row">
            <label>Số lượng câu hỏi </label>
            <input type="number" name="txt_sl"  class="form_input"  id="txt_so_luong_cau_hoi" value="<?php echo @$this->view['data']['so_luong_cau_hoi']?>">
        </div>
        <div class="form_row">
    <label>Câu hỏi </label>
    <input type="text" name="txt_cau_hoi" id="txt_cau_hoi"  value="<?php echo @$xxx; ?>" class="form_input" readonly>
            <span id="btn_brows_question" style="cursor: pointer;color:red;font-weight: bolder"  >Chọn câu hỏi...</span>
        </div>
        <div id="right_wrap">
            <div id="right_content">


            </div>

        </div>
        <div class="form_row">
            <label>Tổng điểm </label>
            <input type="text" class="form_input" name="txt_tong_diem" required value="<?php echo @$this->view['data']['tong_diem']?>" />
        </div>
        <div class="form_row">
            <label>Thời gian làm bài(phút) </label>
            <input type="text" class="form_input" name="txt_tg" value="<?php echo @$this->view['data']['thoi_gian_lam_bai']?>" required />
        </div>
        <div class="form_row">

            <label>Lock</label>
            <input type="radio"  name="txt_lock" value="1" >Khóa <input type="radio"  name="txt_lock" value="0" checked>Không khóa

        </div>

        <div class="form_row">
            <input type="submit" class="form_submit" value="Sửa đề thi" name="btnSave" />
            <?php
            if(!empty($this->view['msg'])){
                $msg1=  new func();
                $msg1->message($this->view['msg']);
            }
            ?>
        </div>
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="Public/backend/js/choncauhoi.js">

</script>
