<?php
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($this->view);
//echo '</pre>';?>
<div class="center_content">


    <div id="right_wrap">
        <div id="right_content">
            <h2>Đề thi</h2>


            <table id="rounded-corner">
                <thead>
                <tr>
                    <th></th>
                    <th>ID</th>
                    <th>Số lượng câu hỏi</th>
                    <th>Tổng điểm</th>
                    <th>Thời gian làm bài</th>
                    <th>Sửa</th>
                    <th>Xóa</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <td colspan="12"></td>
                </tr>
                </tfoot>
                <tbody>
                <tr class="odd">

                    <?php
                    foreach($this->view['list'] as $row){

                        //?controller=admin-group&action=edit&id=14
                        $link = '?controller=admin-test&action=edit&id='.$row['ma_dt'];
                        $link_delete = '?controller=admin-test&action=delete&id='.$row['ma_dt'];


                        echo '<tr><td></td><td>'.$row['ma_dt'].'</td><td>'.$row['so_luong_cau_hoi'].'</td><td>'.$row['tong_diem'].'</td><td>'.$row['thoi_gian_lam_bai'].'</td><td><a href='.$link.'><img src="Public/backend/images/edit.png" alt="" title="" border="0" /></a></td><td><a href='.$link_delete.'><img src="Public/backend/images/trash.gif" alt="" title="" border="0" /></a></td></tr>';

                    }

                    ?>


                </tr>
                <tr><td></td><td></td><td></td><td></td><td></td><td>
                        <?php

                        // hiển thị chỉ số trang của danh sách
                        if($this->view['total_pages']>1){?>

                        <div class="page-number">
                            <ul>
                                <?php
                                for($page = 1; $page <=$this->view['total_pages'];$page ++ ){
                                    echo '<li><a href="?controller=admin-test&action=list&page='.$page.'">'.$page.'</a></li>';
                                }
                                ?>
                                <?php }?>
                    </td></tr>


                </tbody>
            </table>


            <div class="form_sub_buttons">
                <a href="?controller=admin-test&&action=add" class="button green">Thêm đề thi</a>
                <!--<a href="#" class="button red">Delete selected</a>-->
            </div>



        </div>
    </div><!-- end of right content-->

    <div class="sidebar" id="sidebar">
        <h2>Quản lý </h2>

        <ul>
            <li><a href="?controller=admin-test&&action=lock" >Khóa đề thi</a></li>

            <li><a href="#"></a></li>
        </ul>

        <h2>Help</h2>

        <ul>
            <li><a href="#">Help</a></li>
        </ul>

        <h2>Text Section</h2>
        <div class="sidebar_section_text">
            Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </div>

    </div>


    <div class="clear"></div>
</div> <!--end of center_content-->
