<?php
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($this->view);
//echo '</pre>';?>


    <div id="right_wrap">
        <div id="right_content1">
            <h2>Danh Sách Câu Hỏi</h2>


            <table id="rounded-corner" name="txt_ch" <?php echo isset($this->view['list_sub'])?"":"hidden"; ?>>
                <thead>
                <tr>
                    <th></th>
                    <th style='width: 30px'> <input type="checkbox" name="checkbox" id="checkbox" ></th>
                    <th>mã câu hỏi</th>
                    <th>Nội Dung câu hỏi</th>

                    <th>Mã học phần</th>

                </tr>
                </thead>
                <tfoot>
                <tr>
                    <td colspan="12"></td>
                </tr>
                </tfoot>
                <tbody>
                <tr class="odd">

                    <?php
                        if(isset($this->view['list_sub'])){
                            foreach(@$this->view['list_sub'] as $row){

                                echo '<tr><td></td>
                                    <td>
                                        <input type="checkbox" name="cid[]" id="cid" value="'.$row['ma_ch'].'"> 
                                    </td>
                                    <td>'.$row['ma_ch'].'</td>
                                    <td>'.substr($row['noi_dung_ch'],0,100).'</td>
                                    <td>'.$row['id_hp'].'</td>
                                 
                 
                                 </tr>';

                            }
                        }
                        else{
                            echo "Không tồn tại câu hỏi nào";
                        }


                    ?>



                </tr>
                <tr><td></td><td></td><td></td><td>
<!--                        --><?php

                        // hiển thị chỉ số trang của danh sách
                        if($this->view['total_pages']>1){?>

                        <div class="page-number">
                            <ul>
                                <?php
                                $mamh=$this->view['list_sub'][0]['ma_mh'];
                                for($page = 1; $page <=$this->view['total_pages'];$page ++ ){
                                    echo '<li><a href="?controller=admin-test&action=list-ch&ma_mh='.$mamh.'&page='.$page.'">'.$page.'</a></li>';
                                }
                                ?>
                                <?php }?>
                            </ul>
                    </td></tr>


                </tbody>
            </table>


            <br><div class="form_sub_buttons">
                <input type="button" class="form_submit" <?php echo isset($this->view['list_sub'])?"":"hidden"; ?> onclick="setSelectedQuestion();" value="Lưu vào đề thi" style="cursor: pointer"/>

            </div>


        </div>
    </div><!-- end of right content-->




    <div class="clear"></div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>

<script type="text/javascript">
</script>
