
<!DOCTYPE html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Thí Sinh</title>
        <link rel="stylesheet" type="text/css" href="Public/backend/style.css" />
        <link rel="stylesheet" type="text/css" href="Public/frontend/style.css" />
        <link rel="stylesheet" href="Public/Back-end/css/bootstrap.min.css">
        <script>var  _base_url="<?php echo base_path; ?>"</script>
        <script type="text/javascript" src="Public/backend/js/ckeditor/ckeditor.js"></script>
        <script src="Public/backend/js/jquery.min.js"></script>
        
    </head>
    <body>
    <div class="container-fluid"style="position:absolute;top:20px">
    
        <div class="row">  
            <div class="col-xs-12 clearfix " style ="border-bottom:1px solid #e1e5e8; padding-bottom:10px">
                <div class="row">
                    <div class="col-xs-6 "> 
                    <img class="admin-logo img-fluid" src="Public/imgs/images.jpg" alt="" width="100px" style="float:left"  />
                    <h2 style ="display:inline-block ;color: #0d4f77;" class="header-title">Hệ thống thi trắc nghiệm</h2>
                        
                    </div>
                  
                    <div style="margin-top:20px" class="col-xs-6 ">
                        <div class="infor text-right">
                        <?php if(isset($_SESSION['userLogin']))
                                echo 'Xin chao <b>'. $_SESSION['userLogin']['username'].'</b>';
                            ?>
                            <!-- <a href="?controller=admin-user&action=edit" class="settings">Thông tin cá nhân</a>-->
                            
                            <a href="?controller=index&action=logout" class="logout"><i class="fas fa-sign-out-alt"></i>Logout</a>
                    </div>
                </div>
            </div>      
        </div>
            <div class="col-xs-12 clearfix">
                <?php
                $this->showContent();
                ?>
            </div>
           <!--
            // <div class="col-xs-12">
                 <div class="footer text-center">
                <small>Hệ Thống Thi Trắc Nghiệm Trực Tuyến</small> 
                 <small>Thông Tin Liên Hệ <i class = "fa fa-envelope"></i> <a href="mailto:thaothung.04@gmail.com">thaothung.04@gmail.com</a></small>
            </div>
             </div> 
            -->
        </div>
    </div>
        
        
       
        
    </body>
</html>