
<!DOCTYPE html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Thí Sinh</title>
        <link rel="stylesheet" type="text/css" href="Public/backend/style.css" />
        <link rel="stylesheet" type="text/css" href="Public/frontend/style.css" />
        <link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'>
        <script>var  _base_url="<?php echo base_path; ?>"</script>
        <script type="text/javascript" src="Public/backend/js/ckeditor/ckeditor.js"></script>
        <script src="Public/backend/js/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    </head>
    <body>
        <div id="panelwrap " class="edit_layout">
            <div class="header">
                <div class="title"><a href="#">Thí Sinh</a>
                    <div class="infor">
                    <?php if(isset($_SESSION['userLogin']))
                            echo 'Xin chao <b>'. $_SESSION['userLogin']['username'].'</b>';
                        ?>
                        <!-- <a href="?controller=admin-user&action=edit" class="settings">Thông tin cá nhân</a>-->
                        
                        <a href="?controller=index&action=logout" class="logout"><i class="fas fa-sign-out-alt"></i>Logout</a>
                    </div>
                    
                </div>
                
            </div>

            <?php
            $this->showContent();
            ?>

            
        </div> 
        <div class="clear"></div> 
        <div class="footer">
            <small>Hệ Thống Thi Trắc Nghiệm Trực Tuyến</small> 
            <small>Thông Tin Liên Hệ <i class = "fa fa-envelope"></i> <a href="mailto:thaothung.04@gmail.com">thaothung.04@gmail.com</a></small>
        </div>
        
    </body>
</html>