<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Thi Trắc Nghiệm</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <!-- Google Fonts
		============================================ -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700,900" rel="stylesheet">
    <!-- Bootstrap CSS
		============================================ -->
    <!-- <link rel="stylesheet" href="Public/DataTables/DataTables/datatables.css"> -->
    <link rel="stylesheet" type="text/css" href="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.4/css/jquery.dataTables.css">

    <link rel="stylesheet" href="Public/Back-end/css/bootstrap.min.css">
    <!-- Bootstrap CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/font-awesome.min.css">
    <!-- owl.carousel CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/owl.carousel.css">
    <link rel="stylesheet" href="Public/Back-end/css/owl.theme.css">
    <link rel="stylesheet" href="Public/Back-end/css/owl.transitions.css">
    <!-- animate CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/animate.css">
    <!-- normalize CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/normalize.css">
    <!-- meanmenu icon CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/meanmenu.min.css">
    <!-- main CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/main.css">
    <!-- educate icon CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/educate-custon-icon.css">
    <!-- morrisjs CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/morrisjs/morris.css">
    <!-- mCustomScrollbar CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/scrollbar/jquery.mCustomScrollbar.min.css">
    <!-- metisMenu CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/metisMenu/metisMenu.min.css">
    <link rel="stylesheet" href="Public/Back-end/css/metisMenu/metisMenu-vertical.css">
    <!-- calendar CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/calendar/fullcalendar.min.css">
    <link rel="stylesheet" href="Public/Back-end/css/calendar/fullcalendar.print.min.css">
    <!-- style CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/style.css">
    <!-- responsive CSS
		============================================ -->
    <link rel="stylesheet" href="Public/Back-end/css/responsive.css">
    <!-- modernizr JS
		============================================ -->
    <script src="Public/Back-end/js/vendor/modernizr-2.8.3.min.js"></script>
    <script>var  _base_url="<?php echo base_path; ?>"</script>
    <script type="text/javascript" src="Public/backend/js/ckeditor/ckeditor.js"></script>
</head>

<body>
  
	
	
    <!-- Start Left menu area -->
    <div class="left-sidebar-pro">
        <nav id="sidebar" class="">
            <div class="sidebar-header">
                <a href="index.html"><img class="admin-logo img-fluid" src="Public/imgs/images.jpg" alt=""  /></a>
            
            </div>
            <div class="left-custom-menu-adp-wrap comment-scrollbar">
                <nav class="sidebar-nav left-sidebar-menu-pro">
                    <ul class="metismenu" id="menu1">
                        <li class="active">
                            <a class="has-arrow" href="index.html">
								   <span class="educate-icon educate-home icon-wrap"></span>
								   <span class="mini-click-non">Tài khoản</span>
								</a>
                            <ul class="submenu-angle" aria-expanded="true">
                                <li>
                            <a class="has-arrow"  aria-expanded="false"><span class="educate-icon educate-student icon-wrap"></span> <span class="mini-click-non">Học Sinh</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="All Students" href="?controller=teacher-student&action=list"><span class="mini-sub-pro">Danh sách học sinh</span></a></li>
                        
                            </ul>
                        </li>
                        
                            </ul>
                        </li>
                        
                        
                        <li>
                            <a class="has-arrow"  aria-expanded="false"><span class="educate-icon educate-department icon-wrap"></span> <span class="mini-click-non">Lớp</span></a>
                            <ul class="submenu-angle" aria-expanded="false">
                                <li><a title="Departments List" href="?controller=teacher-class&action=list&page=1"><span class="mini-sub-pro">Danh sách lớp</span></a></li>
                                
                               
                            </ul>
                        </li>
                        
                        <li id="removable">
                            <a class="has-arrow" aria-expanded="false"><span class="educate-icon educate-pages icon-wrap"></span> <span class="mini-click-non">Pages</span></a>
                            <ul class="submenu-angle page-mini-nb-dp" aria-expanded="false">
                                <li><a title="Login" href="login.html"><span class="mini-sub-pro">Login</span></a></li>
                                <li><a title="404 Page" href="404.html"><span class="mini-sub-pro">404 Page</span></a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </nav>
    </div>
     <!-- Start Welcome area -->
     <div class="all-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="logo-pro">
                    <!--  <a href="index.html"><img class="main-logo" src="img/logo/logo.png" alt="" /></a>-->
                    </div>
                </div>
            </div>
        </div>
        <div class="header-advance-area">
            <div class="header-top-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="header-top-wraper">
                                <div class="row">
                                    <div class="col-lg-1 col-md-0 col-sm-1 col-xs-12">
                                        <div class="menu-switcher-pro">
                                            <button type="button" id="sidebarCollapse" class="btn bar-button-pro header-drl-controller-btn btn-info navbar-btn">
													<i class="educate-icon educate-nav"></i>
												</button>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-md-7 col-sm-6 col-xs-12">
                                        <div class="header-top-menu tabl-d-n">
                                            <ul class="nav navbar-nav mai-top-nav">
                                                <li class="nav-item"><a href="?controller=teacher-question&action=list&page=1">Ngân hàng câu hỏi</a></li>  
                                                <li class="nav-item"><a href="?controller=teacher-exam&action=list&page=1">Đề thi</a></li>  
                                                <li class="nav-item"><a href="?controller=teacher-exam&action=list-kq-lop">Xem kết quả</a></li>  
                                                <li class="nav-item dropdown res-dis-nn">
                                                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">Thống kê<span class="angle-down-topmenu"><i class="fa fa-angle-down"></i></span></a>
                                                    <div role="menu" class="dropdown-menu animated zoomIn">
                                                        <a href="#" class="dropdown-item">Thống kê thí sinh</a>
                                                        <a href="#" class="dropdown-item">Thống kê đề</a>
                                                       
                                                    </div>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                                        <div class="header-right-info">
                                            <ul class="nav navbar-nav mai-top-nav header-right-menu">

                                                <li class="nav-item">
                                                    <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="nav-link dropdown-toggle">
															<img src="img/product/pro4.jpg" alt="" />
															<span class="admin-name"><?php if(isset($_SESSION['userLogin']))
                                                                echo 'Xin chao <b>'. $_SESSION['userLogin']['username'].'</b>';
                                                            ?></span>
															<i class="fa fa-angle-down edu-icon edu-down-arrow"></i>
														</a>
                                                    <ul role="menu" class="dropdown-header-top author-log dropdown-menu animated zoomIn">
                                                        <li><a href="?controller=index&action=logout"><span class="edu-icon edu-locked author-log-ic"></span>Log Out</a>
                                                        </li>
                                                    </ul>
                                                </li>
                                               
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          
    
        <div>
            <?php
            $this->showContent();
            ?>
        </div>
           
        <div class="footer-copyright-area">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="footer-copy-right">
                            <p>Copyright © 2019. By <a href="mailto:thaothung.04@gmail.com">thaothung.04@gmail.com</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <!-- jquery
		============================================ -->
    <script src="Public/Back-end/js/vendor/jquery-1.12.4.min.js"></script>

    <!-- bootstrap JS
		============================================ -->
    <script src="Public/Back-end/js/bootstrap.min.js"></script>
    
    <script src="Public/Back-end/js/data-table/bootstrap-table.js"></script>
    <script src="Public/Back-end/js/data-table/tableExport.js"></script>
    <script src="Public/Back-end/js/data-table/data-table-active.js"></script>
    <script src="Public/Back-end/js/data-table/bootstrap-table-editable.js"></script>
    <script src="Public/Back-end/js/data-table/bootstrap-editable.js"></script>
    <script src="Public/Back-end/js/data-table/bootstrap-table-resizable.js"></script>
    <script src="Public/Back-end/js/data-table/colResizable-1.5.source.js"></script>
    <script src="Public/Back-end/js/data-table/bootstrap-table-export.js"></script>
    <!-- wow JS
		============================================ -->
    <script src="Public/Back-end/js/wow.min.js"></script>
    <!-- price-slider JS
		============================================ -->
    <script src="Public/Back-end/js/jquery-price-slider.js"></script>
    <!-- meanmenu JS
		============================================ -->
    <script src="Public/Back-end/js/jquery.meanmenu.js"></script>
    <!-- owl.carousel JS
		============================================ -->
    <script src="Public/Back-end/js/owl.carousel.min.js"></script>
    <!-- sticky JS
		============================================ -->
    <script src="Public/Back-end/js/jquery.sticky.js"></script>
    <!-- scrollUp JS
		============================================ -->
    <script src="Public/Back-end/js/jquery.scrollUp.min.js"></script>
    <!-- counterup JS
		============================================ -->
    <script src="Public/Back-end/js/counterup/jquery.counterup.min.js"></script>
    <script src="Public/Back-end/js/counterup/waypoints.min.js"></script>
    <script src="Public/Back-end/js/counterup/counterup-active.js"></script>
    <!-- mCustomScrollbar JS
		============================================ -->
    <script src="Public/Back-end/js/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="Public/Back-end/js/scrollbar/mCustomScrollbar-active.js"></script>
    <!-- metisMenu JS
		============================================ -->
    <script src="Public/Back-end/js/metisMenu/metisMenu.min.js"></script>
    <script src="Public/Back-end/js/metisMenu/metisMenu-active.js"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="Public/Back-end/js/morrisjs/raphael-min.js"></script>
    <script src="Public/Back-end/js/morrisjs/morris.js"></script>
    <script src="Public/Back-end/js/morrisjs/morris-active.js"></script>
    <!-- morrisjs JS
		============================================ -->
    <script src="Public/Back-end/js/sparkline/jquery.sparkline.min.js"></script>
    <script src="Public/Back-end/js/sparkline/jquery.charts-sparkline.js"></script>
    <script src="Public/Back-end/js/sparkline/sparkline-active.js"></script>
    <!-- calendar JS
		============================================ -->
    <script src="Public/Back-end/js/calendar/moment.min.js"></script>
    <script src="Public/Back-end/js/calendar/fullcalendar.min.js"></script>
    <script src="Public/Back-end/js/calendar/fullcalendar-active.js"></script>
    <!-- plugins JS
		============================================ -->
    <script src="Public/Back-end/js/plugins.js"></script>
    <!-- main JS
		============================================ -->
    <script src="Public/Back-end/js/main.js"></script>
  
    
</body>
   

</body>

</html>