<?php
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($this->view);
//echo '</pre>';?>
<div class="center_content ">
    <div id="right_wrap">
        <div id="right_content" class="nomargin">
        <h2><i class="fas fa-school"></i> Danh Sách Bài Thi Đã Thêm</h2>

            <table id="rounded-corner" style="margin:10px ">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>Đề Thi</th>
                    <th>Lớp</th>
                    
                </tr>
                </thead>
                <tfoot>
                
                </tfoot>
                <tbody>
                <tr class="odd">

                    <?php
                    $stt = 0;
                    foreach($this->view['list'] as $row){
                        $stt++;
                       
                        echo '<tr>
                            <td>'.$stt.'</td>
                            <td>'.$row['ma_dt'].'</td>
                            <td>'.$row['ten_lop'].'</td></tr>';
                           

                    }

                    ?>


                </tr>
                </tbody>
            </table>


            

        </div>
    </div><!-- end of right content-->
   


    <div class="clear"></div>
</div> <!--end of center_content-->
