<?php
//echo '<pre>'.__FILE__.'::'.__METHOD__.'('.__LINE__.')';
//    print_r($this->view);
//echo '</pre>';?>
<div class="center_content ">
    <div id="right_wrap">
        <div id="right_content" class="nomargin">
        <h2><i class="fas fa-school"></i> Danh Sách Bài Thi Đã Thêm</h2>

            <table id="rounded-corner" style="margin:10px ">
                <thead>
                <tr>
                    <th>STT</th>
                    <th>Đề Thi</th>
                    <th>Lớp</th>
                    
                </tr>
                </thead>
                <tfoot>
                <tr>
                <td colspan="6">
                        <?php

                        // hiển thị chỉ số trang của danh sách
                        if($this->view['total_pages']>1){?>

                        <div class="page-number">
                            <ul>
                                <?php
                                for($page = 1; $page <=$this->view['total_pages'];$page ++ ){
                                    echo '<li><a href="?controller=admin-baithi&action=list&page='.$page.'">'.$page.'</a></li>';
                                }
                                ?>
                                <?php }?>
                    </td>
                </tr>
                </tfoot>
                <tbody>
                <tr class="odd">

                    <?php
                    $stt = 0;
                    foreach($this->view['list'] as $row){
                        $stt++;
                       
                        echo '<tr>
                            <td>'.$stt.'</td>
                            <td>'.$row['ma_dt'].'</td>
                            <td>'.$row['ten_lop'].'</td></tr>';
                           

                    }

                    ?>


                </tr>
                </tbody>
            </table>


            

        </div>
    </div><!-- end of right content-->
   


    <div class="clear"></div>
</div> <!--end of center_content-->
